=== axel-freesp/xsd2go/examples/test2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.freesp.de/xml/freeSP/test2"
            xmlns="http://www.freesp.de/xml/freeSP/test2"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            elementFormDefault="qualified">

    <xsd:complexType name="Test1">
        <xsd:sequence>
            <xsd:element name="element1" type="Element1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Element1">
        <xsd:sequence>
            <xsd:element name="element2" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:attribute name="arg1" type="xsd:string"/>
                    <xsd:attribute name="arg2" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="test1" type="xsd:integer"/>
        <xsd:attribute name="test2" type="xsd:string"/>
    </xsd:complexType>

    <xsd:element name="test1" type="Test1"/>
</xsd:schema>

=== axel-freesp/xsd2go/examples/test2/test2-test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<test1 xmlns="http://www.freesp.de/xml/freeSP/test2"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.freesp.de/xml/freeSP/test2 ../test2.xsd">
    <element1 test1="-12" test2="doo">
        <element2 arg1="foo" arg2="true"/>
        <element2 arg1="bar" arg2="true"/>
        <element2 arg1="too" arg2="false"/>
    </element1>
    <element1 test1="17" test2="hoo">
        <element2 arg1="moo" arg2="true"/>
        <element3 attr="buu"/>
    </element1>
</test1>
